// Code generated by sqlc.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"github.com/google/uuid"
	"github.com/masb0ymas/go-utils/sql"
)

type Role struct {
	ID        uuid.UUID    `db:"id" json:"id"`
	CreatedAt sql.NullTime `db:"created_at" json:"created_at"`
	UpdatedAt sql.NullTime `db:"updated_at" json:"updated_at"`
	DeletedAt sql.NullTime `db:"deleted_at" json:"deleted_at"`
	Name      string       `db:"name" json:"name"`
}

type User struct {
	ID          uuid.UUID      `db:"id" json:"id"`
	CreatedAt   sql.NullTime   `db:"created_at" json:"created_at"`
	UpdatedAt   sql.NullTime   `db:"updated_at" json:"updated_at"`
	DeletedAt   sql.NullTime   `db:"deleted_at" json:"deleted_at"`
	Fullname    string         `db:"fullname" json:"fullname"`
	Email       string         `db:"email" json:"email"`
	Password    sql.NullString `db:"password" json:"password"`
	Phone       sql.NullString `db:"phone" json:"phone"`
	TokenVerify sql.NullString `db:"token_verify" json:"token_verify"`
	Address     sql.NullString `db:"address" json:"address"`
	IsActive    bool           `db:"is_active" json:"is_active"`
	IsBlocked   bool           `db:"is_blocked" json:"is_blocked"`
	RoleID      uuid.UUID      `db:"role_id" json:"role_id"`
}
